### ISSUE TITLE
Component for responsive images

### ISSUE THREAD

**Issue by chris-perts** [PERTS/perts-ui#21]
Should maintain aspect ratio and resize along with the window.

Spawned from https://github.com/PERTS/saturn/pull/230

See also https://github.com/PERTS/triton/blob/master/src/components/AspectRatio/index.js

**Comment by taptapdan** [comment]
Once this is done, we can close https://github.com/PERTS/saturn/issues/187 by using this component.

**Comment by taptapdan** [comment]
I think all we need is something like:

```js
const Img = styled.img`
  ${(props) =>
    props.responsive &&
    css`
      max-width: 100%;
      height: auto;
    `};

  ${(props) =>
    props.responsive && props.scaleUp
    css`
      width: 100%;
    `};
`;
```

**Comment by taptapdan** [comment]
- include some best practices example in storybook
- include some links to documentation explaining choices
- etc.
